### ISSUE TITLE
Issue Registering Server with IP

### ISSUE THREAD

**Issue by KalebMatthews** [WithOneVisionTechnologies/omnihive-manager-vscode#6]
When a server is registered with an IP it is not added to your servers list.

**Comment by doug-shontz** [comment]
This is "technically fixed" as of 4.0.3.  The connection string with IP is being built correctly.  But, don't mistake this as a "real TCP socket" where you can just have the IP and port.  You can...but only with WS...not with WSS.  Since WS and WSS are web protocols, they are subject to the same SSL rules.  If the network admin has the server set up correctly, all scenarios of building a connection string should work.

For us particularly, you and I can go over this Monday so you understand what's happening between the front and the back-end (particularly with regards to IIS).
